# Generated by Django 5.2.1 on 2025-05-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('meaning', models.TextField()),
                ('translation', models.TextField()),
                ('method', models.CharField(choices=[('flashcard', 'Flashcard'), ('active reading', 'Active Reading'), ('language learning apps', 'Language Learning Apps')], default='flashcard', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
